server.port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    cz.mendelu.ja.leteckaposta: DEBUG


